version: '3.8'
name: cuca-cuda
services:
  jplx:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    ports:
      - "8000:8888"
    volumes:
      - ./venus:/home/venus
      - ./workspace:/opt/workspace
